workflows: get DTS_VER from tag not dts-distro.conf
Dasharo/meta-dts pull request #141
Opened 2024-07-08 14:03 UTC by tym2k1

Test will fail if conflicting versions are present in the push tag and `meta-dts/meta-dts-distro/conf/distro/dts-distro.conf`.

Needs testing before merging

2024-07-18 12:38 UTC, m-iwanicki commented
Won't those changes need to be also added to `develop.yaml`?

2024-07-18 13:56 UTC, tym2k1 commented
You're right. Added the same check to `.develop.yml`  (but with stripping of the `-*` part) and adjusted the syntax of steps to fetch the DTS_VER from GH Actions environmental variable.

2024-07-18 13:57 UTC, tym2k1 commented
[Here's a successfull run of `develop` workflow](https://github.com/Dasharo/meta-dts/actions/runs/9992535037/job/27618098880)

2024-07-19 05:51 UTC, m-iwanicki requested changes
Error should probably explain why this error happens in a way that doesn't require someone to look into code.

2024-07-19 05:51 UTC, m-iwanicki commented on .github/workflows/ci.yml
> +            echo "Expected DTS_VER (${DTS_VER_EXPECTED}) does not match DTS_VER (${DTS_VER_ACTUAL}) in `meta-dts/meta-dts-distro/conf/distro/dts-distro.conf`"
```suggestion
            echo "Tag (${DTS_VER_EXPECTED}) does not match version in `meta-dts/meta-dts-distro/conf/distro/dts-distro.conf` (${DTS_VER_ACTUAL})"
```

2024-07-19 05:51 UTC, m-iwanicki commented on .github/workflows/develop.yml
> +            echo "Expected DTS_VER (${DTS_VER_EXPECTED}) does not match DTS_VER (${DTS_VER_ACTUAL}) in `meta-dts/meta-dts-distro/conf/distro/dts-distro.conf`"
```suggestion
            echo "Tag (${DTS_VER_EXPECTED}) does not match version in `meta-dts/meta-dts-distro/conf/distro/dts-distro.conf` (${DTS_VER_ACTUAL})"
```

2024-07-19 10:07 UTC, tym2k1 commented on .github/workflows/ci.yml
> +            echo "Expected DTS_VER (${DTS_VER_EXPECTED}) does not match DTS_VER (${DTS_VER_ACTUAL}) in `meta-dts/meta-dts-distro/conf/distro/dts-distro.conf`"
[Adressed](https://github.com/Dasharo/meta-dts/blob/d70e66972cc8514cb6056fcd96130ed18e1db3d7/.github/workflows/ci.yml#L82)

2024-07-19 10:08 UTC, tym2k1 commented on .github/workflows/develop.yml
> +            echo "Expected DTS_VER (${DTS_VER_EXPECTED}) does not match DTS_VER (${DTS_VER_ACTUAL}) in `meta-dts/meta-dts-distro/conf/distro/dts-distro.conf`"
[Adressed](https://github.com/Dasharo/meta-dts/blob/d70e66972cc8514cb6056fcd96130ed18e1db3d7/.github/workflows/develop.yml#L81)

2024-07-19 14:19 UTC, tym2k1 commented
> Looks good to me

Please resolve all change requests then

2024-07-19 14:56 UTC, m-iwanicki commented
@tym2k1 done

2024-07-22 22:18 UTC, merged