Add UEFI Capsule update support
Dasharo/meta-dts pull request #154
Opened 2024-08-06 12:42 UTC by DaniilKl

2024-09-10 11:51 UTC, DaniilKl commented
This PR depends on merging https://github.com/Dasharo/dts-scripts/pull/26.

2024-10-17 14:24 UTC, DaniilKl commented
Some rebasing done

2024-10-19 20:39 UTC, DaniilKl commented
Refspec of dts-scripts [will be chenged here](https://github.com/Dasharo/dts-scripts/pull/26#pullrequestreview-2379715381)

2024-11-20 11:32 UTC, DaniilKl commented
Should be merged after https://github.com/Dasharo/dts-scripts/pull/26.

2024-11-20 13:36 UTC, m-iwanicki requested changes

2024-11-20 13:36 UTC, m-iwanicki commented on meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
> +SRCREV = "875887465755cde563da5dcfe67d5c530664b662"
```suggestion
SRCREV = "e757053cae37453cbd7dfaebf0f1a1676829fb25"
```

2024-11-20 13:39 UTC, DaniilKl commented on meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
> +SRCREV = "875887465755cde563da5dcfe67d5c530664b662"
https://github.com/Dasharo/meta-dts/compare/fa25ddb4ed6db4c0e4180425353013f23b3bb287..9de3b6b38940576c1ac4d56d3785e390e9773df5

2024-11-20 13:41 UTC, m-iwanicki approved these changes
LGTM

2024-11-20 13:42 UTC, merged