linux-yocto: remove deprecated kconfig entries
Dasharo/meta-dts pull request #157
Opened 2024-09-05 14:44 UTC by dancios

CONFIG_INTEL_MENLOW & CONFIG_EFI_VARS are deprecated

2024-09-05 14:59 UTC, m-iwanicki requested changes

2024-09-05 19:36 UTC, macpijan commented on meta-dts-distro/recipes-kernel/kernel/linux-yocto/efivars.cfg
> -CONFIG_EFI_VARS=y
Empty file does not make sense. We should either remove it or replace with the new config.

I have discussed with @dancios and we have agreed that Daniel will provide:
1. Result o checking whether the CONFIG_EFI_VARS is used anywhere in the kernel. If it is not, then it does not do anything anyway, so we can safely remove it.
2. Check if our config perhaps has EFIVAR_FS already enabled.

This explanation should come with this path. I do not see it either here or in the issue: https://github.com/Dasharo/dasharo-issues/issues/833

2024-09-05 19:49 UTC, macpijan commented on meta-dts-distro/recipes-kernel/kernel/linux-yocto/efivars.cfg
> -CONFIG_EFI_VARS=y
FWIW, we have used efivar sysfs here: https://github.com/Dasharo/dts-scripts/blob/main/scripts/dts-boot#L8

What would be the interface with this new config? Perhaps we shall modify the scripts as well?

2024-09-06 15:07 UTC, dancios commented
@macpijan @m-iwanicki Updated PR

2024-09-06 15:10 UTC, m-iwanicki commented
@dancios You should answer in review comment if this change fixes it with link do commit/diff. In case of force push you can use link from `Compare` button
![image](https://github.com/user-attachments/assets/118f0487-de90-4f13-82a2-b1169b33f243)

2024-09-06 15:13 UTC, dancios commented on meta-dts-distro/recipes-kernel/kernel/linux-yocto/efivars.cfg
> -CONFIG_EFI_VARS=y
@macpijan @m-iwanicki The efivarsfs will be sent in v2. the entries are the same so no changes to apps shold be made.

2024-09-06 15:41 UTC, dancios commented
> @dancios You should answer in review comment if this change fixes it with link do commit/diff. In case of force push you can use link from `Compare` button ![image](https://private-user-images.githubusercontent.com/143994810/365215046-118f0487-de90-4f13-82a2-b1169b33f243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzczNTAsIm5iZiI6MTcyNTYzNzA1MCwicGF0aCI6Ii8xNDM5OTQ4MTAvMzY1MjE1MDQ2LTExOGYwNDg3LWRlOTAtNGYxMy04MmEyLWIxMTY5YjMzZjI0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNTM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGNkYzJiZDgxM2E1ZGY3ZWFlZjgxZmI5MjI0OWMzMzc0M2RmNDUxNDU5NWYzZjg4ODU4NzQ4ZjU5YjgyMGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yVPZJ4dhZ6tQN6ob3qDeh39EPyE3-VQofCJDwVPkgA4)

Thx for valuable advices I applied suggested changes in previous "comment-thread". They really improve process.

2024-09-11 11:50 UTC, closed without merging