Fix build warnings on DTS #833
Dasharo/meta-dts pull request #167
Opened 2024-09-11 11:48 UTC by dancios

Fixes Dasharo/dasharo-issues#833

2024-09-11 11:55 UTC, dancios commented on meta-dts-distro/recipes-kernel/kernel/linux-yocto/efivars.cfg
> -CONFIG_EFI_VARS=y
resolves Dasharo/dts-scripts#29
This change is also requiere if this is sufficient

2024-09-27 13:48 UTC, m-iwanicki requested changes

2024-09-27 13:48 UTC, m-iwanicki commented on meta-dts-distro/recipes-gnome/gcab/gcab_%.bbappend
> +do_package_qa[noexec] = "1"
Can you use `insane_skip+=buildpaths` as in wolfssl so we don't need to disable whole qa check?

2024-09-27 13:48 UTC, m-iwanicki commented on meta-dts-distro/recipes-kernel/kernel/linux-yocto_%.bbappend
> -    file://efivars.cfg \
Do we use this file or not? If not then delete file too if yes then this line probably should be here.

2024-09-27 13:54 UTC, m-iwanicki commented
Build completes successfully without warnings. 2 comments to be addressed and this PR can be merged.

2024-10-21 11:26 UTC, m-iwanicki commented on meta-dts-distro/recipes-gnome/gcab/gcab_%.bbappend
> +do_package_qa[noexec] = "1"
647703793a3ae0b2f7bbc95a0f15d6407b6cff04

2024-10-21 11:27 UTC, m-iwanicki commented on meta-dts-distro/recipes-kernel/kernel/linux-yocto_%.bbappend
> -    file://efivars.cfg \
35d1227ef133879e42e9072991dc5d9616860f11

2024-10-22 15:14 UTC, m-iwanicki commented
@PLangowski Minimal test on QEMU. It didn't work as QEMU can't be updated (yet).
Update started automatically.

```
Dasharo Tools Suite 2.0.0 DasharoToolsSuite ttyS0

DasharoToolsSuite login: root (automatic login)

Waiting for network connection ...
Network connection have been established!
Waiting for network connection ...
Network connection have been established!
Checking if board is Dasharo compatible.
Board vendor: Emulation is currently not supported
Gathering flash chip and chipset information...
Flash information: vendor="ST" name="M95M02"
Flash size: 0M
Firmware Update Mode detected; proceed with automatic update in 5 seconds
Updating in 5s:
5...
4...
3...
2...
1...
Waiting for system clock to be synced ...
Checking for the latest Dasharo update available...
Current Dasharo version: 0.2.0
Latest available Dasharo version:
ERROR Invalid version ''
Incorrect version format
Update cannot be performed
Starting bash session - please make sure you get logs from
/var/local/dts-err.log and /var/local/flashrom.log; then you can poweroff the platform
```

2024-10-23 11:18 UTC, m-iwanicki commented
To test `Firmware Update Mode` with custom build

1. Enter BIOS -> Dasharo System Features -> Dasharo Security Options -> Enter Firmware Update Mode
2. Accept
3. Press correct key when asked
4. After `iPXE initialising devices... ok` finishes and you see `iPXE 1.21.1+ (g83861) -- Open Source Network Boot Firmware` message press CTRL+C once. After that enter `iPXE Shell` and boot custom DTS.

2024-11-14 09:12 UTC, m-iwanicki approved these changes

2024-11-15 11:26 UTC, artur-rs commented
@PLangowski changes to be included in the v2.1.0 release

2024-11-15 11:28 UTC, merged