Release v2.0.0
Dasharo/meta-dts pull request #177
Opened 2024-09-27 12:55 UTC by PLangowski

2024-09-27 13:22 UTC, m-iwanicki requested changes
Fix pre-commit errors

2024-09-27 13:26 UTC, m-iwanicki requested changes
Do we use unit_tests here? Wasn't it migrated to https://github.com/Dasharo/dts-scripts/tree/main/tests?
Same with scripts directory

2024-09-27 13:28 UTC, m-iwanicki commented
Those are most likely changes done during rebase right?
https://github.com/Dasharo/meta-dts/compare/4018b3a4973f3c9d5102b1dccdd467736d3eba25..096e89db0cc24565926f158d93790de17d77f1ed

They need to be checked very carefully.

2024-09-27 13:44 UTC, PLangowski commented
@m-iwanicki I deleted the files 01b684668a435fb2d645822060eb4404625822da
The other fixes I already did before

2024-09-28 17:16 UTC, m-iwanicki requested changes

2024-09-30 11:35 UTC, PLangowski commented on CHANGELOG.md
> -* Update versions of coreboot-utils
Added back 79c892b99faf3f74aa467c7f3aa29f3c0b15cfed

2024-09-30 11:37 UTC, PLangowski commented on meta-dts-distro/recipes-devtool/python/python3-roca-detect_git.bb
>  SRCREV = "df6071d502f68701427f8b1d409cab22055ad1b7"
I'm leaning towards removing this tool, as I don't think it's being used. @macpijan what do you think?

2024-10-01 16:03 UTC, macpijan commented on meta-dts-distro/recipes-devtool/python/python3-roca-detect_git.bb
>  SRCREV = "df6071d502f68701427f8b1d409cab22055ad1b7"
Since some improvement work has already been done, I have merged it rather than removing altogether.

2024-10-02 10:29 UTC, m-iwanicki approved these changes

2024-10-02 13:24 UTC, artur-rs approved these changes

2024-10-02 13:34 UTC, merged